/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alinket_libraryffmpeg_FFmpegJNI */

#ifndef _Included_com_alinket_libraryffmpeg_FFmpegJNI
#define _Included_com_alinket_libraryffmpeg_FFmpegJNI
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
